---
- name: create group
  group:
    name: www-data
    system: yes

- name: create user
  user:
    name: www-data
    group: www-data
    system: yes
    createhome: no
    home: "{{ caddy_home_dir }}"
    shell: /sbin/nologin

- name: create caddy config directories
  file:
    state: directory
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: 0750
  with_items:
    - "/etc/caddy"
    - "/etc/ssl/caddy"

- name: create caddy home directory
  file:
    state: directory
    path: "{{ caddy_home_dir }}"
    owner: www-data
    group: www-data
    mode: 0755

- name: create caddy log directory
  file:
    state: directory
    path: "/var/log/caddy"
    owner: www-data
    group: www-data
    mode: 0755

- name: determine installed caddy version
  shell: caddy version | awk '{ print $1 }' || true
  register: caddy_version_output

- name: set caddy_installed_version and caddy_version fact
  set_fact: 
    caddy_installed_version: "{{ caddy_version_output.stdout | regex_replace('v') }}"
    caddy_version: "{{ caddy_version | regex_replace('v') }}"

- name: install caddy
  shell: |
    set -e
    cd `mktemp -d`
    curl -fsSL -o caddy.tar.gz 'https://github.com/caddyserver/caddy/releases/download/v{{caddy_version}}/caddy_{{caddy_version}}_linux_amd64.tar.gz'
    tar -xf caddy.tar.gz
    install -m 0755 caddy /usr/local/bin/caddy
    setcap 'cap_net_bind_service=+ep' /usr/local/bin/caddy
  when: caddy_installed_version != caddy_version
  notify: restart caddy

- name: install caddyfile
  copy:
    src: "{{ caddy_file }}"
    dest: /etc/caddy/Caddyfile
    owner: www-data
    group: www-data
  notify: reload caddy

- name: install caddy.service
  copy:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
  notify: restart caddy

- name: enable caddy.service
  systemd:
    name: caddy
    enabled: true
    state: started
